export enum EnumLanguageLevel {
  BEGINNER = "BEGINNER", // A1
  ELEMENTARY = "ELEMENTARY", // A2
  INTERMEDIATE = "INTERMEDIATE", // B1
  UPPER_INTERMEDIATE = "UPPER_INTERMEDIATE", // B2
  ADVANCED = "ADVANCED", // C1
  PROFICIENT = "PROFICIENT", // C2
}

