export enum EnumSessionStatus {
  CREATED = "CREATED",
  AWAITING_PAYMENT_CONFIRMATION = "AWAITING_PAYMENT_CONFIRMATION",
  PAID = "PAID",
  CANCELLED_BY_PATIENT = "CANCELLED_BY_PATIENT",
  CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR",
  // CANCELLED_BY_ADMIN = "CANCELLED_BY_ADMIN",
  CANCELLED_DUE_TO_TIME_OUT = "CANCELLED_DUE_TO_TIME_OUT",
  PAYMENT_FAILED = "PAYMENT_FAILED",
  COMPLETED = "COMPLETED",
}
