export enum SessionStatus {
  CREATED = "CREATED",
  AWAITING_PAYMENT_CONFIRMATION = "AWAITING_PAYMENT_CONFIRMATION",
  PAID = "PAID",
  CANCELLED = "CANCELLED",
  CANCELLED_BY_DOCTOR = "CANCELLED_BY_DOCTOR",
  CANCELLED_DUE_TO_TIME_OUT = "CANCELLED_DUE_TO_TIME_OUT",
  PAYMENT_FAILED = "PAYMENT_FAILED",
}
