export enum EnumStatusCode {
  BAD_REQUEST = "BAD_REQUEST",
  SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",
  UNAUTHORIZED = "UNAUTHORIZED",
  VALIDATION_ERROR = "VALIDATION_ERROR",
  EXISTS_ALREADY = "EXISTS_ALREADY",
  CREATED_SUCCESSFULLY = "CREATED_SUCCESSFULLY",
  UPDATED_SUCCESSFULLY = "UPDATED_SUCCESSFULLY",
  NOT_FOUND = "NOT_FOUND",
  SPECIALTY_NOT_FOUND = "SPECIALTY_NOT_FOUND",
  EXPERTISE_NOT_FOUND = "EXPERTISE_NOT_FOUND",
  NOT_ALLOWED = "NOT_ALLOWED",
  DOCTOR_NOT_FOUND = "DOCTOR_NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",

  ACCOUNT_DELETED = "ACCOUNT_DELETED",
  ACCOUNT_DEACTIVATED = "ACCOUNT_DEACTIVATED",
  TOKEN_REFRESHED = "TOKEN_REFRESHED",

  NO_ACCESS_TOKEN = "NO_ACCESS_TOKEN",
  ACCESS_TOKEN_EXPIRED = "ACCESS_TOKEN_EXPIRED",
  CANNOT_DECODE_ACCESS_TOKEN = "CANNOT_DECODE_ACCESS_TOKEN",

  RECOVERED_SUCCESSFULLY = "RECOVERED_SUCCESSFULLY",

  FILE_TYPE_MISMATCH = "FILE_TYPE_MISMATCH",
  FILE_TOO_LARGE = "FILE_TOO_LARGE",
  NO_FILE_UPLOADED = "NO_FILE_UPLOADED",

  DELETED_SUCCESSFULLY = "DELETED_SUCCESSFULLY",
  DOCTOR_DEACTIVATED = "DOCTOR_DEACTIVATED",

  INVALID_TIME_GAP = "INVALID_TIME_GAP",
  OVERLAP_EXISTS = "OVERLAP_EXISTS",
  BOLD_TIME_ERROR = "BOLD_TIME_ERROR",

  LOGGED_IN_SUCCESSFULLY = "LOGGED_IN_SUCCESSFULLY",
  NOT_SAME_DAY = "NOT_SAME_DAY",

  PERIOD_OCCUPIED = "PERIOD_OCCUPIED",
  PATIENT_NOT_FOUND = "PATIENT_NOT_FOUND",
  PERIOD_NOT_FOUND = "PERIOD_NOT_FOUND",
  PERIOD_PASSED = "PERIOD_PASSED",
  PERIOD_TOO_CLOSE_TO_START = "PERIOD_TOO_CLOSE_TO_START",
  PAYMENT_ERROR = "PAYMENT_ERROR",

  TIMEOUT = "TIMEOUT",
  SESSION_NOT_FOUND = "SESSION_NOT_FOUND",
  TOO_LATE_TO_PAY = "TOO_LATE_TO_PAY",
  SESSION_PAID_ALREADY = "SESSION_PAID_ALREADY",
  CAN_ONLY_PAY_FOR_CREATED_OR_AWAITING_PAYMENT_CONFIRMATION_SESSION = "CAN_ONLY_PAY_FOR_CREATED_OR_AWAITING_PAYMENT_CONFIRMATION_SESSION",
}
