export enum EnumTranzakCurrency {
  XAF = "XAF",
}

export enum EnumTranzakPaymentStatus {
  PENDING = "PENDING",
  SUCCESSFUL = "SUCCESSFUL",
  CANCELLED = "CANCELLED",
  CANCELLED_BY_PAYER = "CANCELLED_BY_PAYER",
  FAILED = "FAILED",
  PAYMENT_IN_PROGRESS = "PAYMENT_IN_PROGRESS",
  CANCELLED_REFUNDED = "CANCELLED/REFUNDED",
  PAYER_REDIRECT_REQUIRED = "PAYER_REDIRECT_REQUIRED",
}

export enum EnumTranzakRefundStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  ON_HOLD = "ON_HOLD",
  SUCCESSFUL = "SUCCESSFUL",
  CANCELLED = "CANCELLED",
  FAILED = "FAILED",
}

export enum EnumTranzakEventType {
  REQUEST_COMPLETED = "REQUEST.COMPLETED",
  REFUND_COMPLETED = "REFUND.COMPLETED",
}

export enum EnumTranzakReasonCode {
  MUTUAL_AGREEMENT_BETWEEN_BUYER_AND_SELLER = 1,
  ORDER_DID_NOT_MATCH_TRANSACTION_AGREEMENT = 2,
  SUSPICIOUS_TRANSACTION = 3,
  DISPUTED_TRANSACTION = 4,
  OTHER_REASONS = 5,
  DEFICIENT_PRODUCT_OR_SERVICE = 6,
  DUPLICATE_TRANSACTION = 7,
  PURCHASED_ITEM_NOT_DELIVERED_BY_MERCHANT = 8,
}
