export enum EnumTranzakCurrency {
  XAF = "XAF",
}

export enum EnumTranzakPaymentStatus {
  PENDING = "PENDING",
  SUCCESSFUL = "SUCCESSFUL",
  CANCELLED = "CANCELLED",
  CANCELLED_BY_PAYER = "CANCELLED_BY_PAYER",
  FAILED = "FAILED",
  PAYMENT_IN_PROGRESS = "PAYMENT_IN_PROGRESS",
  CANCELLED_REFUNDED = "CANCELLED/REFUNDED",
  PAYER_REDIRECT_REQUIRED = "PAYER_REDIRECT_REQUIRED",
}

export enum EnumTranzakEventType {
  REQUEST_COMPLETED = "REQUEST.COMPLETED",
}
